//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExempleUtilisationBoVoyageFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assurance
    {
        public int NumeroUniqueAssurance { get; set; }
        public string SouscriptionAnnulation { get; set; }
        public int NumeroUniqueDossier { get; set; }
    
        public virtual DossiersReservation DossiersReservation { get; set; }
    }
}
