//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExempleUtilisationBoVoyageFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossiersReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DossiersReservation()
        {
            this.Participants = new HashSet<Participants>();
        }
    
        public int NumeroUniqueDossier { get; set; }
        public int NumeroUniqueClient { get; set; }
        public string NumeroCarteBancaire { get; set; }
        public decimal PrixTotal { get; set; }
        public int NumeroUniqueVoyage { get; set; }
        public int NombreParticipant { get; set; }
        public int NumeroUniqueAssurance { get; set; }
    
        public virtual Assurances Assurances { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Voyages Voyages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participants> Participants { get; set; }
    }
}
