//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExempleUtilisationBoVoyageFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voyages()
        {
            this.DossiersReservation = new HashSet<DossiersReservation>();
        }
    
        public int NumeroUniqueVoyage { get; set; }
        public int NumeroUniqueDestination { get; set; }
        public int NumeroUniqueAgence { get; set; }
        public System.DateTime DateAller { get; set; }
        public System.DateTime DateRetour { get; set; }
        public int PlacesDisponibles { get; set; }
        public decimal TarifToutCompris { get; set; }
    
        public virtual AgencesVoyage AgencesVoyage { get; set; }
        public virtual Destinations Destinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DossiersReservation> DossiersReservation { get; set; }
    }
}
